name: Deploy a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: surge ./ https://KeydelM.surge.sh --token $SURGE_TOKEN
